export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
export { default as PrivateRoute } from './PrivateRoute'
export { default as Dashboard } from './Dashboard'
export { default as Friends } from './Friends'
export { default as Account } from './Account'